### ISSUE TITLE
请问为何要用macbert初始化

### ISSUE THREAD

**Issue by xilinniao123** [AxotZero/image_title_match#1]
感谢分享！请问您为何要用 “macbert 的 word_embedding 及 encoder layers 直接 assign 到 visual_bert 的 word_embedding 和 encoder 中“，为何不直接用 visual_bert  的预训练权重？

**Comment by AxotZero** [comment]
您好，因为原始 visual_bert 并没有 pretrained 在中文上面过，word_embedding 也是英文的，这里只是单纯想要用 visual_bert 的架构，直接 assign 即可获得 pretrain 在中文上的 macbert 的权重。
